### ISSUE TITLE
Failed to import Bob, use a slower version of mfcc instead

### ISSUE THREAD

**Issue by McShooty** [ppwwyyxx/speaker-recognition#3]
Hello, I've been trying to use your application but everytime I try to run gui.py or even speaker-recognition.py I get this warning message : "Failed to import Bob, use a slower version of mfcc instead". The thing is bob and his packages are installes and I have no idea how to use a slower version of mfcc. 
Can I get some help please ?

**Comment by ppwwyyxx** [comment]
Try import bob in a python shell:
```python
import bob
import bob.ap
```
It may fail at some line. Bob has lots of packages, maybe you only installed some of them?

The error message means that it's already using a slower version. No need to worry.

**Comment by McShooty** [comment]
Thanks for the reply. I have tried but I get the same errors. Here is the complete list of the errors I get when I try to execute gui.py : 

Warning: failed to import Bob, use a slower version of MFCC instead.
Warning: failed to import fast-gmm, use gmm from scikit-learn instead

(process:1834): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Gtk-Message: Failed to load module "canberra-gtk-module"

(python2:1834): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Qt: Session management error: None of the authentication protocols specified are supported

I'm pretty sure I have installed all the bob packages needed

**Comment by ppwwyyxx** [comment]
If you try:
```
cd src/feature
python2 -c 'import BOB'
```
you'll see the details of the error you're having.

It seems that the rest part of the error are because DBus or Qt on your system are not running properly. This could be caused of different reasons, and I can't tell what's happening.

If you're running it remotely with ssh, then make sure using `ssh -X` because GUI are not supported with plain ssh. If this doesn't solve your problem,  you may want to find someone around you who knows about GNU/Linux to see what's going on exactly.
